//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class bch_tham_gia_hop
    {
        public int thang { get; set; }
        public int nam { get; set; }
        public int id_thanh_vien { get; set; }
    
        public virtual thanh_vien thanh_vien { get; set; }
        public virtual thanh_vien thanh_vien1 { get; set; }
        public virtual hop_bch hop_bch { get; set; }
        public virtual hop_bch hop_bch1 { get; set; }
    }
}
