//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class hop_bch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hop_bch()
        {
            this.bch_tham_gia_hop = new ObservableCollection<bch_tham_gia_hop>();
            this.bch_tham_gia_hop1 = new ObservableCollection<bch_tham_gia_hop>();
        }
    
        public int thang { get; set; }
        public int nam { get; set; }
        public int lan_hop { get; set; }
        public string noi_dung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<bch_tham_gia_hop> bch_tham_gia_hop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<bch_tham_gia_hop> bch_tham_gia_hop1 { get; set; }
    }
}
