//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class khoan_thu
    {
        public int id_thu { get; set; }
        public string noi_dung_thu { get; set; }
        public decimal so_tien { get; set; }
        public int id_nguoi_thu { get; set; }
        public Nullable<int> id_nguoi_nop_tien { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual dong_gop dong_gop { get; set; }
        public virtual dong_gop dong_gop1 { get; set; }
        public virtual thanh_vien thanh_vien { get; set; }
        public virtual thanh_vien thanh_vien1 { get; set; }
        public virtual thanh_vien thanh_vien2 { get; set; }
        public virtual thanh_vien thanh_vien3 { get; set; }
    }
}
