//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class khoan_chi
    {
        public int id_chi { get; set; }
        public string noi_dung_chi { get; set; }
        public int id_hoat_dong { get; set; }
        public decimal so_tien { get; set; }
        public bool da_duyet { get; set; }
        public Nullable<int> id_nguoi_duyet { get; set; }
        public Nullable<System.DateTime> ngay_duyet { get; set; }
    
        public virtual hoat_dong hoat_dong { get; set; }
        public virtual hoat_dong hoat_dong1 { get; set; }
        public virtual thanh_vien thanh_vien { get; set; }
        public virtual thanh_vien thanh_vien1 { get; set; }
    }
}
