//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiNguoiCaoTuoi.DATA
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class hoat_dong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoat_dong()
        {
            this.khoan_chi = new ObservableCollection<khoan_chi>();
            this.khoan_chi1 = new ObservableCollection<khoan_chi>();
            this.thanh_vien_tham_gia = new ObservableCollection<thanh_vien_tham_gia>();
            this.thanh_vien_tham_gia1 = new ObservableCollection<thanh_vien_tham_gia>();
        }
    
        public int id_hoat_dong { get; set; }
        public string tieu_de { get; set; }
        public string noi_dung { get; set; }
        public Nullable<System.DateTime> ngay_bat_dau { get; set; }
        public Nullable<System.DateTime> ngay_ket_thuc { get; set; }
        public Nullable<int> diem_chuan { get; set; }
        public Nullable<int> tu_cham_diem { get; set; }
        public string ket_qua_dat_duoc { get; set; }
        public int nam { get; set; }
    
        public virtual tong_ket tong_ket { get; set; }
        public virtual tong_ket tong_ket1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<khoan_chi> khoan_chi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<khoan_chi> khoan_chi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<thanh_vien_tham_gia> thanh_vien_tham_gia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<thanh_vien_tham_gia> thanh_vien_tham_gia1 { get; set; }
    }
}
