//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiNguoiCaoTuoi.DATA
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class V_ThongKe_MucDoHoatDong
    {
        public int id_thanh_vien { get; set; }
        public string ho_ten { get; set; }
        public System.DateTime ngay_sinh { get; set; }
        public int SoLanThamGiaHD { get; set; }
        public int SoCLBThamGia { get; set; }
        public int SoLanThamGiaHop { get; set; }
        public int Total { get; set; }
    }
}
