//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiNguoiCaoTuoi.DATA
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class V_ThongKe_TongDiemHoatDong
    {
        public int nam { get; set; }
        public int tong_diem { get; set; }
        public int max { get; set; }
        public double percent { get; set; }
    }
}
