//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiNguoiCaoTuoi.DATA
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class V_ThongKe_ThongTin
    {
        public int TongThanhVien { get; set; }
        public int TongBCH { get; set; }
        public int TongCLB { get; set; }
        public int TongTVThamGiaCLB { get; set; }
    }
}
